version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...

  build:
    commands:
      - echo Building static website...
      - echo Nothing to compile

  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - '**/*'
